name:                 BiGUL
version:              1.1.1.0
visibility:           public
id:                   BiGUL-1.1.1.0-B7ChGT1BMAAKT0WLuqXBZi
key:                  BiGUL-1.1.1.0-B7ChGT1BMAAKT0WLuqXBZi
license:              LicenseRef-PublicDomain
maintainer:
    Josh Ko <hsiang-shang@nii.ac.jp> and Zirun Zhu <zhu@nii.ac.jp>

author:
    Josh Ko, Tao Zan, Li Liu, Zirun Zhu, Jorge Mendes, and Zhenjiang Hu

homepage:             http://www.prg.nii.ac.jp/project/bigul/
synopsis:             The Bidirectional Generic Update Language
description:
    Putback-based bidirectional programming allows the programmer to
    write only one putback transformation, from which the unique
    corresponding forward transformation is derived for free. BiGUL,
    short for the Bidirectional Generic Update Language, is designed to
    be a minimalist putback-based bidirectional programming language.
    BiGUL was originally developed in the dependently typed programming
    language Agda, and its well-behavedness has been completely formally
    verified; this package is the Haskell port of BiGUL.

    For more detail, see the following paper:

    * Hsiang-Shang Ko, Tao Zan, and Zhenjiang Hu. BiGUL: A formally
    verified core language for putback-based bidirectional programming.
    In /Partial Evaluation and Program Manipulation/, PEPM’16,
    pages 61–72. ACM, 2016. <http://dx.doi.org/10.1145/2847538.2847544>.

category:             Language, Generics, Lenses
abi:                  ab3e3255f83fdd77143a60c838ada293
exposed:              True
exposed-modules:
    Generics.BiGUL Generics.BiGUL.Error Generics.BiGUL.Interpreter
    Generics.BiGUL.Interpreter.Unsafe Generics.BiGUL.Lib
    Generics.BiGUL.Lib.HuStudies Generics.BiGUL.Lib.List
    Generics.BiGUL.TH

hidden-modules:       Generics.BiGUL.PatternMatching GHC.InOut
import-dirs:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\lib\x86_64-windows-ghc-8.8.2\BiGUL-1.1.1.0-B7ChGT1BMAAKT0WLuqXBZi

library-dirs:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\lib\x86_64-windows-ghc-8.8.2\BiGUL-1.1.1.0-B7ChGT1BMAAKT0WLuqXBZi
    C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
    C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin

dynamic-library-dirs:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\lib\x86_64-windows-ghc-8.8.2
    C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
    C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin

data-dir:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\share\x86_64-windows-ghc-8.8.2\BiGUL-1.1.1.0

hs-libraries:         HSBiGUL-1.1.1.0-B7ChGT1BMAAKT0WLuqXBZi
include-dirs:
    C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\include

depends:
    base-4.13.0.0 containers-0.6.8-HRdaVGINqBt2xEd71trvGz mtl-2.2.2
    template-haskell-2.15.0.0 th-extras-0.0.0.4-38YaicbpTlF3wRuruE47oz

haddock-interfaces:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\doc\BiGUL-1.1.1.0\BiGUL.haddock

haddock-html:
    G:\haskell_test\myfirstapp\stack\work\install\0a2fad69\doc\BiGUL-1.1.1.0
