name: BiGUL
version: 1.1.1.0
id: BiGUL-1.1.1.0-5NKogHNZUa0vTRS4yqT2D
key: BiGUL-1.1.1.0-5NKogHNZUa0vTRS4yqT2D
license: PublicDomain
maintainer: Josh Ko <hsiang-shang@nii.ac.jp> and Zirun Zhu <zhu@nii.ac.jp>
homepage: http://www.prg.nii.ac.jp/project/bigul/
synopsis: The Bidirectional Generic Update Language
description:
    Putback-based bidirectional programming allows the programmer to
    write only one putback transformation, from which the unique
    corresponding forward transformation is derived for free. BiGUL,
    short for the Bidirectional Generic Update Language, is designed to
    be a minimalist putback-based bidirectional programming language.
    BiGUL was originally developed in the dependently typed programming
    language Agda, and its well-behavedness has been completely formally
    verified; this package is the Haskell port of BiGUL.
    .
    For more detail, see the following paper:
    .
    * Hsiang-Shang Ko, Tao Zan, and Zhenjiang Hu. BiGUL: A formally
    verified core language for putback-based bidirectional programming.
    In /Partial Evaluation and Program Manipulation/, PEPM’16,
    pages 61–72. ACM, 2016. <http://dx.doi.org/10.1145/2847538.2847544>.
category: Language, Generics, Lenses
author: Josh Ko, Tao Zan, Li Liu, Zirun Zhu, Jorge Mendes, and Zhenjiang Hu
exposed: True
indefinite: False
exposed-modules:
    Generics.BiGUL Generics.BiGUL.Error Generics.BiGUL.Interpreter
    Generics.BiGUL.Interpreter.Unsafe Generics.BiGUL.Lib
    Generics.BiGUL.Lib.HuStudies Generics.BiGUL.Lib.List
    Generics.BiGUL.TH
hidden-modules: Generics.BiGUL.PatternMatching GHC.InOut
abi: 8c62501a6802597289bfca69c0862329
trusted: False
import-dirs: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\lib\x86_64-windows-ghc-8.2.2\BiGUL-1.1.1.0-5NKogHNZUa0vTRS4yqT2D
library-dirs: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\lib\x86_64-windows-ghc-8.2.2\BiGUL-1.1.1.0-5NKogHNZUa0vTRS4yqT2D
              C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
              C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin
dynamic-library-dirs: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\lib\x86_64-windows-ghc-8.2.2
                      C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\lib
                      C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\bin
data-dir: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\share\x86_64-windows-ghc-8.2.2\BiGUL-1.1.1.0
hs-libraries: HSBiGUL-1.1.1.0-5NKogHNZUa0vTRS4yqT2D
include-dirs: C:\Users\ClanTri\AppData\Local\Programs\stack\x86_64-windows\msys2-20230526\mingw64\include
depends:
    base-4.10.1.0 mtl-2.2.2-8XubxMJDT8QLsstvlNotkc containers-0.5.10.2
    template-haskell-2.12.0.0 th-extras-0.0.0.4-IefxXQ1pZVELhprEbmwKQt
abi-depends: base-4.10.1.0=f58f75ed278e4eb8b022dcfbe263ab20
             mtl-2.2.2-8XubxMJDT8QLsstvlNotkc=db4dc09d3a59faa9d2e553a8ccdd7b59
             containers-0.5.10.2=4be6a0546412d544990a40270e9567c8
             template-haskell-2.12.0.0=1fe65852b90f9b78db653971f9579a1f
             th-extras-0.0.0.4-IefxXQ1pZVELhprEbmwKQt=718b9aa5f9cdf710d436d13ea2ea0cad
haddock-interfaces: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\doc\BiGUL-1.1.1.0\BiGUL.haddock
haddock-html: G:\haskell_test\myfirstapp\stack\work\install\723c8c46\doc\BiGUL-1.1.1.0
